#!/bin/bash
if [ ! -f 'enumerator.cabal' ]; then
	echo -n "Can't find enumerator.cabal; please run this script as"
	echo -n " ./scripts/dist from within the enumerator source"
	echo " directory"
	exit 1
fi

. scripts/common.bash

require_cabal_dev

echo "Building dist for enumerator_$VERSION using $CABAL_DEV"

rm -rf dist
$CABAL_DEV configure || exit 1
$CABAL_DEV build || exit 1
$CABAL_DEV sdist || exit 1

mv "dist/enumerator-$VERSION.tar.gz" "./enumerator_$VERSION.tar.gz"
ln -f "./enumerator_$VERSION.tar.gz" "./enumerator-$VERSION.tar.gz"
if [ -n "$XZ" ]; then
	gzip -dfc "enumerator_$VERSION.tar.gz" > "enumerator_$VERSION.tar"
	xz -f -C sha256 -9 "enumerator_$VERSION.tar"
fi

echo ""
echo "============================================================"
echo "  source archive (gz) : enumerator_$VERSION.tar.gz"
if [ -n "$XZ" ]; then
	echo "  source archive (xz) : enumerator_$VERSION.tar.xz"
fi
echo "============================================================"
