#!/bin/bash
if [ ! -f 'enumerator.cabal' ]; then
	echo -n "Can't find enumerator.cabal; please run this script as"
	echo -n " ./scripts/haddock from within the enumerator source"
	echo " directory"
	exit 1
fi

. scripts/common.bash

require_anansi
require_cabal_dev

rm -rf hs dist
$ANANSI --noline -o hs src/enumerator.anansi || exit 1
$CABAL_DEV configure || exit 1
$CABAL_DEV haddock || exit 1
